---
- name: Create php_action_list
  ansible.builtin.set_fact:
    php_action_list: "{{ php_actions.split(',') }}"

- name: Validate php_action_list
  ansible.builtin.assert:
    that:
      - php_action_list | length > 0
      - php_action_list | difference(php_supported_actions) | length == 0

- name: Run php action
  ansible.builtin.include_tasks: "{{ task_name }}.yml"
  loop: "{{ php_action_list }}"
  loop_control:
    loop_var: task_name
