---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install php8.3 packages
      ansible.builtin.apt:
        name:
          - php8.3
          - php8.3-fpm
          - php8.3-cli
          - php8.3-curl
        state: present
        update_cache: true
